from dataclasses import replace

import pytest

from core.engine.progression import parse_progression
from core.engine.loop_engine import build_progression_score, generate_variant_from_progression
from core.models import GenerationTrace, LoopVariant
from core.presets.registry import get_preset, list_presets
from core.theory.explainer import explain


# Independent spellings: 1, 2, b3, 4, 5, b6, b7, 7, 6, b2.
# These fixtures are not generated by the analysis/transposition implementation.
TONICS = [
    "C D Eb F G Ab Bb B A Db",
    "Db Eb Fb Gb Ab Bbb Cb C Bb Ebb",
    "D E F G A Bb C C# B Eb",
    "Eb F Gb Ab Bb Cb Db D C Fb",
    "E F# G A B C D D# C# F",
    "F G Ab Bb C Db Eb E D Gb",
    "F# G# A B C# D E E# D# G",
    "G A Bb C D Eb F F# E Ab",
    "Ab Bb Cb Db Eb Fb Gb G F Bbb",
    "A B C D E F G G# F# Bb",
    "Bb C Db Eb F Gb Ab A G Cb",
    "B C# D E F# G A A# G# C",
]


def variant(tones, strategy="progression_driven_register_mapped"):
    return LoopVariant(
        id="musical-audit", preset_name="audit", label="Audit",
        musicxml_path=None, midi_path=None, svg_bytes=None, midi_bytes=None,
        theory_explanation=None,
        trace=GenerationTrace(7, strategy, ["mid register"] * len(tones), None, tones),
    )


def example(row, case):
    t, second, third, fourth, fifth, flat6, flat7, leading, sixth, flat2 = row.split()
    tonic = [t, third, fifth]
    cases = {
        "natural": ([tonic + [flat7], [fourth, flat6, t], [fifth, flat7, second]],
                    "i7 -> iv -> v", "natural minor (Aeolian)"),
        "harmonic": ([tonic, [fourth, flat6, t], [fifth, leading, second, fourth], tonic],
                     "i -> iv -> V7 -> i", "harmonic minor"),
        "dorian": ([tonic + [flat7, second], [fourth, sixth, t, third, fifth]],
                   "i9 -> IV9", "Dorian"),
        "leading-diminished": ([[leading, second, fourth], tonic], "vii° -> i", None),
        "flat-two": ([[flat2, fourth, flat6], tonic], "bII -> i", None),
        "ambiguous": ([tonic], "i", None),
    }
    return cases[case]


@pytest.mark.parametrize("preset_name", list_presets())
@pytest.mark.parametrize("row", TONICS, ids=lambda row: row.split()[0])
@pytest.mark.parametrize("case", ["natural", "harmonic", "dorian", "leading-diminished", "flat-two", "ambiguous"])
def test_independent_harmonic_corpus_in_every_tonic_and_style(preset_name, row, case):
    tones, expected_path, collection = example(row, case)
    tonic = row.split()[0]
    preset = replace(get_preset(preset_name), key_tonic=tonic)
    explanation = explain(variant(tones), preset)
    facts = explanation.why_it_works.split("Style option:")[0]
    assert f"Harmony: {expected_path}." in facts
    assert "reference tonic" in facts
    if collection:
        assert f"fit {tonic} {collection}." in facts
    if case == "ambiguous":
        assert "do not distinguish" in facts
        assert "natural minor (Aeolian)" in facts and "Dorian" in facts
    if case == "natural":
        assert "harmonic minor" not in facts
        assert "raised leading tone" not in facts
    if case == "dorian":
        assert "authentic cadence" not in facts
        assert "natural minor (Aeolian)" not in facts
    if case == "harmonic":
        assert "phrase ending" in facts
    if case == "flat-two":
        assert "Phrygian cadence" not in facts
    assert "strongest pull" not in facts


@pytest.mark.parametrize("tones, expected", [
    (["C#", "E", "G"], "vii°"),
    (["Db", "Fb", "Abb"], "bi°"),
    (["G", "B", "D"], "IV"),
    (["E", "G", "Bb"], "ii°"),
    (["B", "D", "F"], "vi°"),
    (["A", "C#", "E", "G"], "V7"),
    (["D", "F", "A", "C", "E"], "i9"),
])
def test_degree_uses_spelled_root_and_actual_quality(tones, expected):
    preset = get_preset("dorian_sexy_duet")
    assert f"Harmony: {expected}." in explain(variant([tones]), preset).why_it_works


@pytest.mark.parametrize("chord_text, expected", [
    ("Gm", "G-Bb-D"), ("C#", "C#-E#-G#"), ("F#", "F#-A#-C#"),
])
def test_parser_pitch_classes_receive_explicit_tertian_spelling(chord_text, expected):
    tones = [chord.components for chord in parse_progression(chord_text)]
    explanation = explain(variant(tones), get_preset("dark_trip_hop"))
    assert expected in explanation.why_it_works
    if chord_text == "Gm":
        assert "Bb is supplied as A#" in explanation.why_it_works


@pytest.mark.parametrize("tones, expected", [
    (["Cb", "Eb", "Gb"], "Cb-Eb-Gb"),
    (["B#", "D#", "F#"], "B#-D#-F#"),
    (["F#", "A#", "C#", "E#"], "F#-A#-C#-E#"),
    (["C", "Eb", "Gb", "Bbb"], "C-Eb-Gb-Bbb"),
    (["D#", "F##", "A#"], "D#-F##-A#"),
])
def test_theory_preserves_spelled_enharmonics_that_the_parser_may_not_support(tones, expected):
    explanation = explain(variant([tones]), get_preset("dark_trip_hop"))
    assert expected in explanation.why_it_works


def test_minor_chord_does_not_redefine_the_reference_tonic():
    p = replace(get_preset("dark_trip_hop"), key_tonic="C", key_mode="major")
    e = explain(variant([["D", "F", "A"], ["G", "B", "D"], ["C", "E", "G"]]), p)
    assert "In D minor" not in e.how_to_develop
    assert "Harmony: ii -> V -> I." in e.why_it_works
    assert "outside natural C minor" not in e.why_it_works
    assert "back to Cm" not in e.why_it_works


def test_leading_note_inside_tonic_seventh_is_not_a_dominant():
    p = replace(get_preset("noir_slow_burn"), key_tonic="C", key_mode="major")
    e = explain(variant([["C", "E", "G", "B"]]), p)
    facts = e.why_it_works.split("Style option:")[0]
    assert "Harmony: Imaj7." in facts
    assert "pull back" not in facts and "authentic cadence" not in facts


def test_borrowed_minor_four_is_possible_mixture_not_a_key_change():
    p = replace(get_preset("dark_trip_hop"), key_tonic="C", key_mode="major")
    e = explain(variant([["C", "E", "G"], ["F", "Ab", "C"], ["C", "E", "G"]]), p)
    assert "Harmony: I -> iv -> I." in e.why_it_works
    assert "possible borrowing from parallel C natural minor" in e.why_it_works
    assert "Ab" in e.why_it_works


@pytest.mark.parametrize("preset_name", list_presets())
def test_style_policy_does_not_invent_a_cadence_for_one_chord(preset_name):
    p = replace(get_preset(preset_name), key_tonic="D")
    e = explain(variant([["D", "F", "A"]]), p)
    facts = e.why_it_works.split("Style option:")[0]
    assert "cadence" not in facts.lower()
    assert "The loop's harmonic pull comes from" not in e.why_it_works
    assert "Rooted in" not in e.why_it_works
    assert "No chord change" in facts


def test_sequential_line_does_not_become_a_series_of_root_position_chords():
    e = explain(variant([["F2", "A2", "D3"], ["C#3", "D3"]], "preset_verbatim"),
                get_preset("dorian_sexy_duet"))
    assert "sequential cello notes" in e.why_it_works
    assert "Harmony:" not in e.why_it_works
    assert "F major" not in e.why_it_works
    assert "C#" in e.why_it_works


@pytest.mark.parametrize("row", TONICS, ids=lambda row: row.split()[0])
def test_dorian_advice_and_mode_shift_transpose_from_degrees(row):
    t, _, _, _, _, flat6, _, _, sixth, _ = row.split()
    tones, _, _ = example(row, "dorian")
    p = replace(get_preset("dorian_sexy_duet"), key_tonic=t)
    e = explain(variant(tones), p)
    assert f"{sixth} (6)" in e.how_to_develop
    assert f"{sixth} -> {flat6}" in e.how_to_transition
    assert f"{t} Dorian -> {t} natural minor" in e.how_to_transition
    assert "D Dorian vamp: Dm9" not in e.why_it_works


@pytest.mark.parametrize("row", TONICS, ids=lambda row: row.split()[0])
def test_flat_second_advice_approaches_tonic_from_above(row):
    t, *_, flat2 = row.split()
    p = replace(get_preset("dark_trip_hop"), key_tonic=t)
    e = explain(variant([row.split()[0:1]]), p)
    assert f"{flat2} -> {t}" in e.how_to_develop
    assert "semitone above" in e.how_to_develop
    assert "from below" not in e.how_to_develop


def test_minor_dyad_does_not_invent_an_absent_fifth():
    e = explain(variant([["A", "C"]]), get_preset("noir_slow_burn"))
    assert "E stabilizes" not in e.how_to_develop
    assert "incomplete" in e.why_it_works


def test_repeated_harmonies_preserve_order_and_the_return():
    p = get_preset("noir_slow_burn")
    e = explain(variant([["A", "C", "E"], ["E", "G#", "B"], ["A", "C", "E"]]), p)
    assert "Harmony: i -> V -> i." in e.why_it_works


def test_common_tones_are_possible_voice_leading_not_observed_held_voices():
    e = explain(variant([["C", "Eb", "G"], ["Ab", "C", "Eb"]]), get_preset("dark_trip_hop"))
    assert "can be retained" in e.how_to_develop
    assert "stays between" not in e.how_to_develop


@pytest.mark.parametrize("preset_name", ["dark_trip_hop", "ritual_tribal", "noir_slow_burn", "driving_cinematic"])
@pytest.mark.parametrize("bias", ["low", "default", "high"])
def test_parsed_input_score_and_explanation_agree(preset_name, bias):
    from music21 import pitch

    preset = replace(get_preset(preset_name), key_tonic="D")
    chords = parse_progression("Dm9 G9 A7 Dm")
    score = build_progression_score(chords, preset, seed=7, register_bias=bias)
    generated = generate_variant_from_progression(chords, preset, seed=7, register_bias=bias)
    explanation = explain(generated, preset)
    assert "Harmony: i9 -> IV9 -> V7 -> i." in explanation.why_it_works
    # READ-01 caps a bar at a few notes, so a five-tone chord is never sounded
    # in full: every played note must belong to the supplied chord, and the
    # trace must record exactly what was played so the explanation can say so.
    played_by_bar = []
    for measure, parsed in zip(score.parts[0].getElementsByClass("Measure"), chords, strict=True):
        supplied = {pitch.Pitch(name).pitchClass for name in parsed.components}
        played = {note.pitch.pitchClass for note in measure.notes}
        assert played and played <= supplied
        assert len(measure.notes) <= 4
        played_by_bar.append(played)
    assert generated.trace.played_pitches is not None
    for names, played in zip(generated.trace.played_pitches, played_by_bar, strict=True):
        assert {pitch.Pitch(name).pitchClass for name in names} == played
    assert "Chord tones: Dm9: D-F-A-C-E" in explanation.why_it_works
    assert "in this loop Dm9 sounds" in explanation.why_it_works
    assert "B" in explanation.why_it_works and "C#" in explanation.why_it_works
    assert "do not fit a single" in explanation.why_it_works


def test_changing_style_alone_does_not_change_the_musical_facts():
    supplied = variant([["D", "F", "A", "C", "E"], ["Eb", "G", "Bb"]])
    facts = {
        explain(supplied, replace(get_preset(name), key_tonic="D")).why_it_works.split("Style option:")[0]
        for name in list_presets()
    }
    assert len(facts) == 1
    assert "Harmony: i9 -> bII." in facts.pop()


def test_enharmonic_augmented_sixth_reading_is_explicitly_qualified():
    e = explain(variant([["Ab", "C", "Eb", "F#"], ["G", "B", "D"]]), get_preset("dark_trip_hop"))
    assert "Gb is supplied as F#" in e.why_it_works
    assert "enharmonic pitch-class reading" in e.why_it_works


@pytest.mark.parametrize("tones, chord_symbol, numeral", [
    (["C", "Eb", "G", "Bb"], "Cm7", "i7"),
    (["C", "Eb", "G", "B"], "Cm(maj7)", "i(maj7)"),
    (["C", "Eb", "Gb", "Bb"], "Cm7b5", "iø7"),
    (["C", "Eb", "Gb", "Bbb"], "Cdim7", "i°7"),
    (["C", "E", "G#"], "Caug", "I+"),
    (["C", "F", "G"], "Csus4", "Isus4"),
    (["C", "G"], "C5", "I5 (no third)"),
    (["C", "E", "G", "A"], "C6", "I(add6)"),
    (["C", "Eb", "G", "A"], "Cm6", "i(add6)"),
    (["C", "E", "G", "Bb", "Db"], "C7 (plus Db)", "I7 (plus Db)"),
    (["C", "E", "G", "B", "F#"], "Cmaj7 (plus F#)", "Imaj7 (plus F#)"),
])
def test_chord_quality_and_extensions_are_not_lost(tones, chord_symbol, numeral):
    e = explain(variant([tones]), get_preset("dark_trip_hop"))
    assert f"Chord tones: {chord_symbol}:" in e.why_it_works
    assert f"Harmony: {numeral}." in e.why_it_works


@pytest.mark.parametrize("preset_name, collection", [
    ("dark_trip_hop", "C natural minor (Aeolian)"),
    ("driving_cinematic", "C natural minor (Aeolian)"),
    ("ritual_tribal", "D natural minor (Aeolian)"),
    ("noir_slow_burn", None),
    ("sexy_duet", None),
    ("simple_sexy_duet", "D harmonic minor"),
    ("dorian_sexy_duet", "D Dorian"),
])
def test_authored_notes_determine_collection_independently_of_preset_policy(preset_name, collection):
    preset = get_preset(preset_name)
    bars = preset.bars or preset.duet_bars["cello"]
    e = explain(variant([list(bar) for bar in bars], "preset_verbatim"), preset)
    facts = e.why_it_works.split("Style option:")[0]
    if collection:
        assert f"fit {collection}." in facts
    else:
        assert "do not fit a single" in facts
    if preset_name == "ritual_tribal":
        assert "Phrygian" not in facts
    if preset_name == "noir_slow_burn":
        assert "G#" not in facts
